services:

  mysql_db:
    image: mysql:8.0

    container_name: mysql_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: alvaro1981
      MYSQL_DATABASE: cristal_database
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_pass

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  fastapi_app:
    build: .

    container_name: fastapi_app

    restart: always

    depends_on:
      - mysql_db

    ports:
      - "8000:8000"

    volumes:
      - .:/app
      - uploads_data:/app/uploads

    command: >
      sh -c "sleep 10 &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mysql_data:
  uploads_data:
